'use client'
import Head from 'next/head'
import { useState } from 'react'
import CommonTextField from 'src/components/text-filed'

export default function Home() {
  const [text, setText] = useState<string>('')

  return (
    <>
      <Head>
        <title>Next app</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Hello world!</h1>
      <CommonTextField value={text} onChange={setText} inputType='password' />
    </>
  )
}
